/* Copyright (C) 2014-2016 by Jacob Alexander
 *
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this file.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the kll compiler, DO NOT EDIT.
// Generation Date:    2016-08-05
// KLL Backend:        kiibohd
// KLL Git Rev:        12b84b0d43bcc3330dffb1bdd4eae7e58afcfadb
// KLL Git Changes:
//    Keyboards/WhiteFox.gcc/Makefile
//    Keyboards/WhiteFox.gcc/buildvars.h
//    Keyboards/WhiteFox.gcc/generatedKeymap.h
//    Keyboards/WhiteFox.gcc/kll_defs.h
//    Keyboards/WhiteFox.gcc/load
//    kll/layouts/whitefox.kll
//    kll/layouts/whitefox_1.kll
// Compiler arguments:
//    ../../kll/kll.py
//      /Users/jack/projects/controller/Scan/ISSILed/capabilities.kll
//      /Users/jack/projects/controller/Scan/MatrixARM/capabilities.kll
//      /Users/jack/projects/controller/Macro/PartialMap/capabilities.kll
//      /Users/jack/projects/controller/Output/pjrcUSB/capabilities.kll
//      /Users/jack/projects/controller/Scan/WhiteFox/scancode_map.kll
//      -d
//      /Users/jack/projects/controller/kll/layouts/whitefox.kll
//      /Users/jack/projects/controller/kll/layouts/stdFuncMap.kll
//      -p
//      /Users/jack/projects/controller/kll/layouts/whitefox_1.kll
//    --backend
//      kiibohd
//    --templates
//      /Users/jack/projects/controller/kll/templates/kiibohdKeymap.h
//      /Users/jack/projects/controller/kll/templates/kiibohdDefs.h
//    --outputs
//      generatedKeymap.h
//      kll_defs.h
//
// - Base Layer -
//    ISSILedCapabilities
//      /Users/jack/projects/controller/Scan/ISSILed/capabilities.kll
//    MatrixArmCapabilities
//      /Users/jack/projects/controller/Scan/MatrixARM/capabilities.kll
//    PartialMapCapabilities
//      /Users/jack/projects/controller/Macro/PartialMap/capabilities.kll
//    pjrcUSBCapabilities
//      /Users/jack/projects/controller/Output/pjrcUSB/capabilities.kll
//    WhiteFox
//      /Users/jack/projects/controller/Scan/WhiteFox/scancode_map.kll
// - Default Layer -
//    WhiteFox
//      /Users/jack/projects/controller/kll/layouts/whitefox.kll
//    stdFuncMap
//      /Users/jack/projects/controller/kll/layouts/stdFuncMap.kll
// - Partial Layers -
//    Layer 1
//     WhiteFox
//       /Users/jack/projects/controller/kll/layouts/whitefox_1.kll



#pragma once

// ----- Enums -----

// Capability Indices
typedef enum CapabilityIndex {
	LED_control_capability_index,
	Macro_layerLatch_capability_index,
	Macro_layerLock_capability_index,
	Macro_layerRotate_capability_index,
	Macro_layerShift_capability_index,
	Macro_layerState_capability_index,
	Output_consCtrlSend_capability_index,
	Output_flashMode_capability_index,
	Output_kbdProtocolBoot_capability_index,
	Output_kbdProtocolNKRO_capability_index,
	Output_noneSend_capability_index,
	Output_sysCtrlSend_capability_index,
	Output_toggleKbdProtocol_capability_index,
	Output_usbCodeSend_capability_index,
	Output_usbMouse_capability_index,
} CapabilityIndex;



// ----- KLL Variables -----




// ----- Defines -----

// -- Interconnect Node Maximum --
#define InterconnectNodeMax 0x1



#define StateWordSize_define 8
#define ISSILedBrightness1_define  \
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* C1-1 -> C1-16 */ \
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* C2-1 -> C2-16 */ \
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* C3-1 -> C3-16 */ \
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* C4-1 -> C4-16 */ \
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* C5-1 -> C5-16 */ \
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* C6-1 -> C6-16 */ \
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* C7-1 -> C7-16 */ \
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* C8-1 -> C8-16 */ \
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* C9-1 -> C9-16 */ \

#define enableUSBLowPowerNegotiation_define 0
#define enableDeviceRestartOnUSBTimeout_define 0
#define flashModeEnabled_define 0
#define enableVirtualSerialPort_define 1
#define enableKeyboard_define 1
#define USBProtocol_define 1
#define enableJoystick_define 0
#define DebounceThrottleDiv_define 0
#define enableUSBSuspend_define 1
#define enableUSBResume_define 1
#define KeyboardLocale_define 0
#define enableMouse_define 1
#define MinDebounceTime_define 5
#define DebounceDivThreshold_define 65535
#define ISSILedMask1_define  \
	0xFF, 0x00, /* C1-1 -> C1-16 */ \
	0xFF, 0x00, /* C2-1 -> C2-16 */ \
	0xFF, 0x00, /* C3-1 -> C3-16 */ \
	0xFF, 0x00, /* C4-1 -> C4-16 */ \
	0xFF, 0x00, /* C5-1 -> C5-16 */ \
	0xFF, 0x00, /* C6-1 -> C6-16 */ \
	0xFF, 0x00, /* C7-1 -> C7-16 */ \
	0xFF, 0x00, /* C8-1 -> C8-16 */ \
	0xFF, 0x00, /* C9-1 -> C9-16 */ \

#define IndexWordSize_define 16
#define enableRawIO_define 0
#define CapabilitiesNum_KLL 15
#define ResultMacroNum_KLL 90
#define TriggerMacroNum_KLL 103
#define LayerNum_KLL 2

